language: python
python:
  - "3.7"
before_install:
  - git config --global core.sshCommand "ssh -i id_rsa"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - openssl aes-256-cbc -K $encrypted_0cb91c87838c_key -iv $encrypted_0cb91c87838c_iv -in id_rsa.enc -out id_rsa -d
  - chmod 400 id_rsa
install:
  - git checkout master
  - git reset --hard origin/master
  - git remote set-url origin git@github.com:$TRAVIS_REPO_SLUG.git
  - pipenv sync
script:
  - pipenv run python app.py
branches:
  only:
    - master
